src/subscriptions/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

urlpatterns = patterns('src.subscriptions.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'success', name='success'),
)

src/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('src',
    # Examples:
    url(r'^$', 'core.views.homepage', name='homepage'),
    url(
        r'^inscricao/',
        include('src.subscriptions.urls', namespace='subscriptions')
    ),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('src.core.urls', namespace='core')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

src/subscriptions/models.py
# coding: utf-8

from django.db import models


class Subscription(models.Model):

    name = models.CharField('Nome', max_length=100)
    cpf = models.CharField('CPF', max_length=11, unique=True)
    email = models.EmailField('E-mail', blank=True)
    phone = models.CharField('Telefone', max_length=20, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    paid = models.BooleanField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["created_at"]
        verbose_name = u"Inscrição"
        verbose_name_plural = u"Inscrições"

src/subscriptions/forms.py
# coding: utf-8

from django import forms
from .models import Subscription
from django.utils.translation import ugettext as _
from django.contrib.localflavor.br.forms import BRCPFField
from django.core.validators import EMPTY_VALUES


class PhoneWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        attrs_1 = attrs or {}
        attrs_2 = attrs_1.copy()
        attrs_1.update({'size': '1', 'maxlength': '2'})
        attrs_2.update({'size': '10', 'maxlength': '8'})
        widgets = (
            forms.TextInput(attrs=attrs_1),
            forms.TextInput(attrs=attrs_2)
        )
        super(PhoneWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')


class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (
            forms.CharField(),
            forms.CharField(max_length=8,)
        )
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(u'DDD inválido')
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(u'Número inválido')
        return '%s-%s' % tuple(data_list)


class SubscriptionForm(forms.ModelForm):

    name = forms.CharField(label=_('Nome'), max_length=100, widget=forms.TextInput(attrs={'size': '50'}))
    cpf = BRCPFField(label=_('CPF'), max_length=11, widget=forms.TextInput(attrs={'size': '20'}))
    email = forms.EmailField(label=_('E-mail'), required=False, widget=forms.TextInput(attrs={'size': '30'}))
    phone = PhoneField(label=_('Telefone'), required=False)

    def _unique_check(self, fieldname, error_message):
        param = {fieldname: self.cleaned_data[fieldname]}
        try:
            s = Subscription.objects.get(**param)
        except Subscription.DoesNotExist:
            return self.cleaned_data[fieldname]
        raise forms.ValidationError(error_message)

    def clean_email(self):
        return self._unique_check('email', _(u'E-mail já inscrito.'))

    def clean(self):
        super(SubscriptionForm, self).clean()

        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise forms.ValidationError(_(u'Informe seu e-mail ou telefone.'))

        return self.cleaned_data

    class Meta:
        model = Subscription
        exclude = ('paid',)

src/subscriptions/views.py
# coding: utf-8

from django.http import HttpResponseRedirect
from django.views.generic.simple import direct_to_template
from .forms import SubscriptionForm
from django.core.urlresolvers import reverse as r
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import get_object_or_404
from .models import Subscription


def subscribe(request):

    if request.method == 'POST':
        return create(request)
    else:
        return new(request)


def new(request):

    form = SubscriptionForm()
    return direct_to_template(request, 'subscriptions/subscription_form.html', {'form': form})


def create(request):

    form = SubscriptionForm(request.POST)

    if not form.is_valid():
        return direct_to_template(request, 'subscriptions/subscription_form.html', {'form': form})

    subscription = form.save()

    #envia o email
    send_mail(
        subject=u'Cadastrado com Sucesso',
        message=u'Obrigado pela sua inscrição!',
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[subscription.email]
        )

    return HttpResponseRedirect(r('subscriptions:success', args=[subscription.pk]))


def success(request, pk):

    subscription = get_object_or_404(Subscription, pk=pk)
    return direct_to_template(request, 'subscriptions/subscription_detail.html', {'subscription': subscription})

src/subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}

{% block title %}Concluído{% endblock title %}

{% block content %}

	<p>Parabéns {{ subscription.name }},</p>
	<p>sua inscrição foi realizada em {{ subscription.created_at|date:"d/m/Y" }}.</p>
	
	<p>Em breve, entraremos em contato pelo
		{% if subscription.phone %}
			telefone {{ subscription.phone }}
		{% else %}
		    email {{ subscription.email }}
		{% endif %}
	</p>

{% endblock content %}

src/subscriptions/templates/subscriptions/subscription_form.html
{% extends 'base.html' %}

{% block head %}
{% endblock head %}

{% block title %}
Inscrição
{% endblock title %}

{% block content %}

<form action="." method="POST">
    {% csrf_token %}
    
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Nome:</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.cpf.errors }}
        <label for="id_cpf">CPF:</label>
        {{ form.cpf }}
    </div>
    <div class="fieldWrapper">
        {{ form.email.errors }}
        <label for="id_email">E-mail:</label>
        {{ form.email }}
    </div>
    <div class="fieldWrapper">
        {{ form.phone.errors }}
        <label for="id_phone">Telefone:</label>
        {{ form.phone }}
    </div>
    <p><input type="submit" value="Enviar!" class="button"/></p>
</form>

{% endblock content %}